#!/bin/bash
#PBS -P CFP01-CF-060
#PBS -N fineweb_sampling
#PBS -q auto
#PBS -l select=1:ngpus=1
#PBS -l walltime=12:00:00
#PBS -j oe

export APPTAINERENV_TORCHMETRICS_SKIP_IMAGE_DIST_TESTS=1

cd $PBS_O_WORKDIR

module load singularity
IMAGE="/app1/common/singularity-img/hopper/cuda/cuda_12.1.0-cudnn8-devel-u20.04.sif"

singularity exec -e $IMAGE bash << 'EOF' \
    > "/scratch/Projects/CFP-01/CFP01-CF-060/kieron/$PBS_JOBNAME.$PBS_JOBID.stdout.log" \
    2> "/scratch/Projects/CFP-01/CFP01-CF-060/kieron/$PBS_JOBNAME.$PBS_JOBID.stderr.log"

source /hpctmp/e0968891/virtualenvs/cuda/bin/activate
cd /scratch/Projects/CFP-01/CFP01-CF-060/kieron

echo "Starting at $(date)"

python fineweb_sampling.py

EOF