#!/bin/bash
#PBS -P CFP01-CF-060
#PBS -N downstream_mt_3
#PBS -q auto
#PBS -l select=1:ngpus=1
#PBS -l walltime=96:00:00
#PBS -j oe

export APPTAINERENV_TORCHMETRICS_SKIP_IMAGE_DIST_TESTS=1

cd $PBS_O_WORKDIR

module load singularity
IMAGE="/app1/common/singularity-img/hopper/cuda/cuda_12.1.0-cudnn8-devel-u20.04.sif"

singularity exec -e $IMAGE bash << EOF \
    > "/scratch/Projects/CFP-01/CFP01-CF-060/kieron/$PBS_JOBNAME.$PBS_JOBID.stdout.log" \
    2> "/scratch/Projects/CFP-01/CFP01-CF-060/kieron/$PBS_JOBNAME.$PBS_JOBID.stderr.log"

source /hpctmp/e0968891/virtualenvs/cuda/bin/activate

echo "Starting at $(date)"

cd /scratch/Projects/CFP-01/CFP01-CF-060/kieron/blt/downstream

python pipeline_mt.py \
    --model_path /scratch/Projects/CFP-01/CFP01-CF-060/kieron/blt/tmp/step20k \
    --tokenizer_name blt \
    --entropy_model_path /scratch/Projects/CFP-01/CFP01-CF-060/kieron/blt/blt-entropy/50m_mC4 \
    --langs my ta

EOF